In [1]:
import numpy as np

In [7]:
a = np.random.randn(15, 143)

In [8]:
a.shape

(15, 143)

In [9]:
b = np.sum(a, axis = 1)

In [10]:
b.shape

(15,)

In [11]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [12]:
a = np.arange(10)

In [13]:
col_idx = [3, 6, 8]

In [14]:
a[col_idx]

array([3, 6, 8])

In [21]:
a = np.random.randn(5,6)

In [22]:
a

array([[ 0.28174638, -1.31499148, -1.98111361, -0.24362383,  1.91878453,
        -1.33594093],
       [ 0.39845581, -0.46160809, -1.02192241,  0.61191981,  0.31716267,
         2.24703982],
       [ 0.36111188,  0.37663681, -0.54482431, -1.45943142, -0.94345164,
         1.20049203],
       [ 0.88775088, -1.20045849, -0.64879574,  1.03463205,  0.9447499 ,
         1.19295369],
       [ 0.73646462,  0.25672694,  0.58639094, -0.41989796, -0.46480192,
        -1.00806028]])

In [23]:
row_idx = [0, 2, 4]
col_idx = [ 1, 3, 5]

In [24]:
a[row_idx]

array([[ 0.28174638, -1.31499148, -1.98111361, -0.24362383,  1.91878453,
        -1.33594093],
       [ 0.36111188,  0.37663681, -0.54482431, -1.45943142, -0.94345164,
         1.20049203],
       [ 0.73646462,  0.25672694,  0.58639094, -0.41989796, -0.46480192,
        -1.00806028]])

In [25]:
a[:, col_idx]

array([[-1.31499148, -0.24362383, -1.33594093],
       [-0.46160809,  0.61191981,  2.24703982],
       [ 0.37663681, -1.45943142,  1.20049203],
       [-1.20045849,  1.03463205,  1.19295369],
       [ 0.25672694, -0.41989796, -1.00806028]])

In [27]:
np.isnan(a).any()

False