In [1]:
import numpy as np

In [26]:
a = np.ones((5,4))

In [41]:
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [42]:
b = np.array([1,2,3,4])

In [43]:
b.reshape((4,1))

array([[1],
       [2],
       [3],
       [4]])

In [46]:
a - b.T[None, :]

array([[ 0., -1., -2., -3.],
       [ 0., -1., -2., -3.],
       [ 0., -1., -2., -3.],
       [ 0., -1., -2., -3.],
       [ 0., -1., -2., -3.]])

In [9]:
b = np.max(a, axis=1)

In [10]:
b

array([1., 1., 1., 1., 1.])

In [11]:
c = a - b[:, None]

In [12]:
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
d = np.array([2,3,4,5,6]).T

In [21]:
d

array([2, 3, 4, 5, 6])

In [22]:
a/d[:, None]

array([[0.5       , 0.5       , 0.5       , 0.5       ],
       [0.33333333, 0.33333333, 0.33333333, 0.33333333],
       [0.25      , 0.25      , 0.25      , 0.25      ],
       [0.2       , 0.2       , 0.2       , 0.2       ],
       [0.16666667, 0.16666667, 0.16666667, 0.16666667]])

In [23]:
x = [1,2,1,2,3]
y = [3,4,5,6,7]

In [25]:
x+y[:,None]

TypeError: list indices must be integers or slices, not tuple

In [47]:
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [49]:
np.shape(np.sum(a, axis=0))

(4,)

In [50]:
x = np.sum(a, axis=0)

In [51]:
x.reshape((1,4))

array([[5., 5., 5., 5.]])

In [52]:
x = np.ones((5,5))

In [53]:
y = np.sum(x, axis = 0)

In [54]:
y.shape

(5,)

In [55]:
y.reshape((1,5))

array([[5., 5., 5., 5., 5.]])

In [56]:
pi = [1/5] * 5

In [58]:
pi = np.array([1/5] * 5)

In [59]:
pi.shape

(5,)

In [69]:
x = np.array([np.eye(5)]*7)

In [70]:
x.shape

(7, 5, 5)

In [71]:
a = np.random.random((5,4))

In [74]:
a

array([[0.82045738, 0.8781274 , 0.61053101, 0.62482866],
       [0.64799033, 0.21352439, 0.04943654, 0.55788808],
       [0.87323644, 0.34636717, 0.79670612, 0.86040287],
       [0.67550898, 0.94144132, 0.32997169, 0.08494789],
       [0.61810441, 0.8929369 , 0.83841559, 0.29169423]])

In [75]:
b = np.array([1,2,3,4])

In [76]:
b.shape

(4,)

In [73]:
a + b

array([[1.82045738, 2.8781274 , 3.61053101, 4.62482866],
       [1.64799033, 2.21352439, 3.04943654, 4.55788808],
       [1.87323644, 2.34636717, 3.79670612, 4.86040287],
       [1.67550898, 2.94144132, 3.32997169, 4.08494789],
       [1.61810441, 2.8929369 , 3.83841559, 4.29169423]])

In [77]:
a

array([[0.82045738, 0.8781274 , 0.61053101, 0.62482866],
       [0.64799033, 0.21352439, 0.04943654, 0.55788808],
       [0.87323644, 0.34636717, 0.79670612, 0.86040287],
       [0.67550898, 0.94144132, 0.32997169, 0.08494789],
       [0.61810441, 0.8929369 , 0.83841559, 0.29169423]])

In [78]:
b = np.sum(a, axis=1)

In [79]:
b

array([2.93394445, 1.46883934, 2.8767126 , 2.03186989, 2.64115112])

In [81]:
a/b[:, None]

array([[0.27964312, 0.29929926, 0.20809222, 0.2129654 ],
       [0.44115807, 0.14536947, 0.03365687, 0.37981559],
       [0.30355359, 0.12040382, 0.2769502 , 0.2990924 ],
       [0.33245681, 0.46333741, 0.16239804, 0.04180774],
       [0.23402841, 0.33808626, 0.31744325, 0.11044208]])