In [9]:
import numpy as np

In [2]:
a = np.ones((5,6,7))

In [3]:
a.shape

(5, 6, 7)

In [4]:
type(a.shape)

tuple

In [5]:
len(a.shape)

3

In [44]:
img = np.random.rand(100,46,3)

In [45]:
img = img.transpose(2,0,1)

In [46]:
U, V, S = np.linalg.svd(img)

In [47]:
U.shape

(3, 100, 100)

In [48]:
U = U.transpose(1,2,0)

In [49]:
S.shape

(3, 46, 46)

In [50]:
S = S.transpose(1,2,0)

In [51]:
V.shape

(3, 46)

In [52]:
V = V.transpose(1,0)

In [53]:
U.shape

(100, 100, 3)

In [54]:
S.shape

(46, 46, 3)

In [55]:
V.shape

(46, 3)

In [56]:
img = np.random.rand(100,46)

In [57]:
U, V, S = np.linalg.svd(img)

In [58]:
U.shape

(100, 100)

In [59]:
V.shape

(46,)

In [60]:
S.shape

(46, 46)

In [61]:
V = V.reshape((46,1))

In [62]:
V.shape

(46, 1)

In [130]:
a = np.random.rand(4,4)

In [131]:
a

array([[0.83087841, 0.99944675, 0.81171752, 0.88120457],
       [0.08457205, 0.16738736, 0.84061205, 0.36361541],
       [0.1502327 , 0.26814047, 0.878005  , 0.62610042],
       [0.23593673, 0.3634724 , 0.80625987, 0.1832107 ]])

In [132]:
b = np.random.rand(4,4)

In [133]:
b

array([[0.71933013, 0.20655789, 0.4030683 , 0.66757604],
       [0.72610988, 0.53641531, 0.63776749, 0.69960107],
       [0.20984778, 0.48018499, 0.39281323, 0.40288431],
       [0.66798396, 0.44448171, 0.38218884, 0.64419312]])

In [134]:
c = np.random.rand(4,4)

In [135]:
c

array([[0.40881671, 0.08759277, 0.46846453, 0.98202048],
       [0.34070527, 0.25646623, 0.78738676, 0.54554867],
       [0.14216328, 0.45478789, 0.38846165, 0.49712954],
       [0.97740427, 0.20375381, 0.92192449, 0.0374814 ]])

In [136]:
d = np.concatenate((a,b,c),axis=0)

In [137]:
d

array([[0.83087841, 0.99944675, 0.81171752, 0.88120457],
       [0.08457205, 0.16738736, 0.84061205, 0.36361541],
       [0.1502327 , 0.26814047, 0.878005  , 0.62610042],
       [0.23593673, 0.3634724 , 0.80625987, 0.1832107 ],
       [0.71933013, 0.20655789, 0.4030683 , 0.66757604],
       [0.72610988, 0.53641531, 0.63776749, 0.69960107],
       [0.20984778, 0.48018499, 0.39281323, 0.40288431],
       [0.66798396, 0.44448171, 0.38218884, 0.64419312],
       [0.40881671, 0.08759277, 0.46846453, 0.98202048],
       [0.34070527, 0.25646623, 0.78738676, 0.54554867],
       [0.14216328, 0.45478789, 0.38846165, 0.49712954],
       [0.97740427, 0.20375381, 0.92192449, 0.0374814 ]])

In [126]:
d.shape

(4, 12)

In [127]:
d = d.reshape((4,4,3))

In [128]:
d

array([[[0.79958252, 0.57577743, 0.97286611],
        [0.62140331, 0.59356762, 0.92355326],
        [0.43509486, 0.2529063 , 0.7972817 ],
        [0.04929344, 0.61862862, 0.11712154]],

       [[0.2043392 , 0.75321133, 0.82220003],
        [0.51859509, 0.5748785 , 0.10012788],
        [0.5758745 , 0.46938887, 0.22446641],
        [0.32579247, 0.84416519, 0.10851145]],

       [[0.72321965, 0.745559  , 0.60543987],
        [0.26410333, 0.00318846, 0.59182277],
        [0.40311011, 0.2709198 , 0.80352855],
        [0.95328183, 0.73561883, 0.11438251]],

       [[0.00341977, 0.78705223, 0.18309512],
        [0.54274961, 0.56274036, 0.20925351],
        [0.56283436, 0.32706773, 0.16169131],
        [0.74167117, 0.37142152, 0.84846532]]])

In [129]:
d[0]

array([[0.79958252, 0.57577743, 0.97286611],
       [0.62140331, 0.59356762, 0.92355326],
       [0.43509486, 0.2529063 , 0.7972817 ],
       [0.04929344, 0.61862862, 0.11712154]])

In [141]:
d = np.array([ a, b, c])

In [142]:
d

array([[[0.83087841, 0.99944675, 0.81171752, 0.88120457],
        [0.08457205, 0.16738736, 0.84061205, 0.36361541],
        [0.1502327 , 0.26814047, 0.878005  , 0.62610042],
        [0.23593673, 0.3634724 , 0.80625987, 0.1832107 ]],

       [[0.71933013, 0.20655789, 0.4030683 , 0.66757604],
        [0.72610988, 0.53641531, 0.63776749, 0.69960107],
        [0.20984778, 0.48018499, 0.39281323, 0.40288431],
        [0.66798396, 0.44448171, 0.38218884, 0.64419312]],

       [[0.40881671, 0.08759277, 0.46846453, 0.98202048],
        [0.34070527, 0.25646623, 0.78738676, 0.54554867],
        [0.14216328, 0.45478789, 0.38846165, 0.49712954],
        [0.97740427, 0.20375381, 0.92192449, 0.0374814 ]]])

In [146]:
d.shape

(3, 4, 4)

In [147]:
d = d.transpose((1,2,0))

In [148]:
d

array([[[0.83087841, 0.71933013, 0.40881671],
        [0.99944675, 0.20655789, 0.08759277],
        [0.81171752, 0.4030683 , 0.46846453],
        [0.88120457, 0.66757604, 0.98202048]],

       [[0.08457205, 0.72610988, 0.34070527],
        [0.16738736, 0.53641531, 0.25646623],
        [0.84061205, 0.63776749, 0.78738676],
        [0.36361541, 0.69960107, 0.54554867]],

       [[0.1502327 , 0.20984778, 0.14216328],
        [0.26814047, 0.48018499, 0.45478789],
        [0.878005  , 0.39281323, 0.38846165],
        [0.62610042, 0.40288431, 0.49712954]],

       [[0.23593673, 0.66798396, 0.97740427],
        [0.3634724 , 0.44448171, 0.20375381],
        [0.80625987, 0.38218884, 0.92192449],
        [0.1832107 , 0.64419312, 0.0374814 ]]])

In [176]:
a = np.random.rand(4,2)

In [177]:
b = np.random.rand(4,2)

In [178]:
c = np.random.rand(4,2)

In [179]:
a

array([[0.12012167, 0.93930051],
       [0.38979732, 0.87039167],
       [0.46735675, 0.9744732 ],
       [0.94915224, 0.57610124]])

In [180]:
b

array([[0.04005673, 0.098835  ],
       [0.42422706, 0.52309798],
       [0.02162245, 0.50936877],
       [0.8282791 , 0.31551878]])

In [181]:
c

array([[0.45010337, 0.48449115],
       [0.38513817, 0.04635381],
       [0.15307824, 0.80972781],
       [0.0941948 , 0.97621781]])

In [182]:
d = np.array([ a,b,c])

In [183]:
d

array([[[0.12012167, 0.93930051],
        [0.38979732, 0.87039167],
        [0.46735675, 0.9744732 ],
        [0.94915224, 0.57610124]],

       [[0.04005673, 0.098835  ],
        [0.42422706, 0.52309798],
        [0.02162245, 0.50936877],
        [0.8282791 , 0.31551878]],

       [[0.45010337, 0.48449115],
        [0.38513817, 0.04635381],
        [0.15307824, 0.80972781],
        [0.0941948 , 0.97621781]]])

In [184]:
d.shape

(3, 4, 2)

In [174]:
d.transpose(1,2,0)

array([[[0.322259  , 0.66388253, 0.05728418],
        [0.54246838, 0.49772267, 0.33137589],
        [0.65473099, 0.5618187 , 0.1949042 ],
        [0.95626936, 0.34197165, 0.44180029]],

       [[0.37580767, 0.32587896, 0.24837822],
        [0.9105897 , 0.64528059, 0.8464461 ],
        [0.64422511, 0.75491962, 0.08698625],
        [0.30291732, 0.95284396, 0.58953165]],

       [[0.92010508, 0.37966538, 0.87992415],
        [0.94105069, 0.0099917 , 0.15792955],
        [0.36013343, 0.67418563, 0.6736781 ],
        [0.13945303, 0.08656883, 0.48766951]],

       [[0.44347737, 0.32415077, 0.20469988],
        [0.71803684, 0.83893394, 0.34703232],
        [0.02582413, 0.04314914, 0.24604344],
        [0.38586443, 0.34039687, 0.6182199 ]]])

In [175]:
d[:, :, 0]

array([[0.322259  , 0.37580767, 0.92010508, 0.44347737],
       [0.66388253, 0.32587896, 0.37966538, 0.32415077],
       [0.05728418, 0.24837822, 0.87992415, 0.20469988]])

In [161]:
img = np.random.rand(100,46)

In [162]:
U, S, V = np.linalg.svd(img)

In [163]:
k = 10

In [164]:
np.matmul(S[1:k], V[:, 1:k])

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 46 is different from 9)

In [192]:
X = np.random.rand(5,3)

In [193]:
X

array([[0.7846132 , 0.07027665, 0.32401259],
       [0.54567238, 0.07131953, 0.93796574],
       [0.58279159, 0.03995588, 0.12204274],
       [0.15613219, 0.8832507 , 0.86885001],
       [0.35535882, 0.40332239, 0.43795355]])

In [194]:
mu = np.mean(X, axis=0)

mu.shape

In [195]:
mu.shape

(3,)

In [196]:
mu

array([0.48491364, 0.29362503, 0.53816493])

In [197]:
X = X - mu

In [198]:
X

array([[ 0.29969956, -0.22334838, -0.21415234],
       [ 0.06075874, -0.2223055 ,  0.39980082],
       [ 0.09787796, -0.25366915, -0.41612218],
       [-0.32878145,  0.58962567,  0.33068508],
       [-0.12955481,  0.10969736, -0.10021137]])

In [199]:
mu = np.mean(X, axis=0)

In [200]:
mu

array([ 2.22044605e-17,  4.44089210e-17, -2.22044605e-17])

In [201]:
X = np.random.rand(150, 4)

In [202]:
mu = np.mean(X, axis=0, keepdims=True)

In [203]:
X = X - mu

In [205]:
U, S, V = np.linalg.svd(X, full_matrices=False)

In [206]:
K=2

In [208]:
X_new = np.dot(U[:, :K], np.diag(S)[:K, :K])

In [209]:
X_new.shape

(150, 2)

In [221]:
a = np.ones((5))

In [222]:
b = np.zeros((5))

In [223]:
np.concatenate((a,b))

array([1., 1., 1., 1., 1., 0., 0., 0., 0., 0.])

In [224]:
x = np.random.rand(58)

In [225]:
degree = 8


In [226]:
N = x.shape[0]
feat = np.ones((N))
for i in range(1, degree + 1):
    x_term = np.power(x, i)
    temp = np.column_stack((feat, x_term))
    feat = temp
        

In [227]:
feat.shape

(58, 9)

In [228]:
a = np.ones((5))

In [229]:
b = np.ones((5)) * 2

In [233]:
a

array([1., 1., 1., 1., 1.])

In [234]:
b

array([2., 2., 2., 2., 2.])

In [235]:
a/b

array([0.5, 0.5, 0.5, 0.5, 0.5])

In [237]:
np.power(b,a)

array([2., 2., 2., 2., 2.])

In [3]:
i = np.identity((7))

In [4]:
i

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [5]:
i[0][0] = 0.0

In [6]:
i

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [7]:
i * 6

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 6., 0., 0., 0., 0., 0.],
       [0., 0., 6., 0., 0., 0., 0.],
       [0., 0., 0., 6., 0., 0., 0.],
       [0., 0., 0., 0., 6., 0., 0.],
       [0., 0., 0., 0., 0., 6., 0.],
       [0., 0., 0., 0., 0., 0., 6.]])

In [8]:
type(i)

numpy.ndarray

In [12]:
X = np.arange(0.001, 1.001, 0.001)

In [13]:
X

array([0.001, 0.002, 0.003, 0.004, 0.005, 0.006, 0.007, 0.008, 0.009,
       0.01 , 0.011, 0.012, 0.013, 0.014, 0.015, 0.016, 0.017, 0.018,
       0.019, 0.02 , 0.021, 0.022, 0.023, 0.024, 0.025, 0.026, 0.027,
       0.028, 0.029, 0.03 , 0.031, 0.032, 0.033, 0.034, 0.035, 0.036,
       0.037, 0.038, 0.039, 0.04 , 0.041, 0.042, 0.043, 0.044, 0.045,
       0.046, 0.047, 0.048, 0.049, 0.05 , 0.051, 0.052, 0.053, 0.054,
       0.055, 0.056, 0.057, 0.058, 0.059, 0.06 , 0.061, 0.062, 0.063,
       0.064, 0.065, 0.066, 0.067, 0.068, 0.069, 0.07 , 0.071, 0.072,
       0.073, 0.074, 0.075, 0.076, 0.077, 0.078, 0.079, 0.08 , 0.081,
       0.082, 0.083, 0.084, 0.085, 0.086, 0.087, 0.088, 0.089, 0.09 ,
       0.091, 0.092, 0.093, 0.094, 0.095, 0.096, 0.097, 0.098, 0.099,
       0.1  , 0.101, 0.102, 0.103, 0.104, 0.105, 0.106, 0.107, 0.108,
       0.109, 0.11 , 0.111, 0.112, 0.113, 0.114, 0.115, 0.116, 0.117,
       0.118, 0.119, 0.12 , 0.121, 0.122, 0.123, 0.124, 0.125, 0.126,
       0.127, 0.128,

In [14]:
X.shape

(1000,)